### ISSUE TITLE
Support for WSSE security with UsernameToken

### ISSUE THREAD

**Issue by Veronit** [bartkl/robotframework-zeeplibrary#12]
Hi,

I was wondering whether ZeepLibrary already supports WSSE security with UsernameToken or not? I wasn't able to use it until I made a small change to the code. 
But since I am not an expert in python or in zeep, I don't know whether the change will break anything else. I have no way in verifying whether the HTTPBasicAuth you have implemented works. I also took a look at the tests you have, but couldn't execute the authentication test.
This is the change I made:

zeeplibrary.py row 245:

client = zeep.Client(wsdl, transport=transport)

to 

client = zeep.Client(wsdl, wsse=UsernameToken(auth[0], auth[1]), transport=transport)

This change is based on this: https://python-zeep.readthedocs.io/en/master/wsse.html

If you are happy with this, I can provide a pull request.

**Comment by bartkl** [comment]
Hello,

Sorry for the delayed response. I haven't had much time or reason to spend much energy on this project.

HTTP Basic authentication should work, although you understandably cannot run the test set I provided. They work only on the LAN of the company I work at. I should make that clear in some way maybe.... It's not very handy haha.

I have no experience using WSSE so I haven't put in any effort to implement it. As far as your suggested edit goes: I don't like using the `auth` argument for both WSSE and HTTP Basic Auth. So, I would rather have  `create_client`  have an extra `wsse` parameter which is then passed on to the client instantiation.

```python
# ...
    @keyword('Create client')
    def create_client(self,
                      wsdl,
                      alias=None,
                      auth=None,
                      wsse=None,  # <-- add this
                      proxies=None,
                      cert=None,
                      verify=None):
        if wsse:
            wsse = UsernameToken(wsse[0], wsse[1]
# ...

```

And then change your code to:

```python
client = zeep.Client(wsdl, wsse=wsse, transport=transport)  # This way `wsse` can be `None` and is therefore optional
```

I assume you have also added `from zeep.wsse.username import UsernameToken` at the top? Did you test the code?

You are welcome to create a pull request after the requested changes, and I hope I'll find the time to look into this again quickly. We can discuss further in the PR :).

Thanks for your additions!

Bart

**Comment by Veronit** [comment]
Closing this because of pull request: https://github.com/bartkl/robotframework-zeeplibrary/pull/13
